services:
  cache:
    container_name: cache
    image: redis:6.0-alpine

  frontend:
    container_name: frontend
#     depends_on:
#       - proxy
    build:
      context: ./frontend
      args:
        NODE_ENV: 'production'
        NEXT_PUBLIC_URL: 'http://localhost/'
        BACKEND_URL: 'https://217.182.78.34/backend/'
        SERVICE_USER_TOKEN: 'kCZkQ7LBNO5LOBbqCts3Kiwpcw_ek5_k'
    command: [ 'start' ]
    environment:
      SERVICE_USER_TOKEN: 'kCZkQ7LBNO5LOBbqCts3Kiwpcw_ek5_k'
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  proxy:
    container_name: proxy
    build: 
      context: ./proxy
      args:
        PROXY_CONF_FILE: './proxy_production.conf'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/certs:/etc/nginx/certs
    # depends_on:
    #   - directus
    #   - frontend

volumes:
  directus_uploads:
  node_modules:
  pg_database: