services:
  cache:
    container_name: cache
    image: redis:6.0-alpine
   
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        NODE_ENV: 'development'
        # NODE_ENV: 'production'
        #NODE_ENV: 'production-archive'
        NEXT_PUBLIC_URL: 'http://localhost/'
        BACKEND_URL: 'http://217.182.78.34/backend/'
        SERVICE_USER_TOKEN: 'kCZkQ7LBNO5LOBbqCts3Kiwpcw_ek5_k'
    command: [ 'dev' ]
    environment:
      SERVICE_USER_TOKEN: 'kCZkQ7LBNO5LOBbqCts3Kiwpcw_ek5_k'
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      args:
        PROXY_CONF_FILE: './proxy_dev.conf'
    ports:
      - 80:80

volumes:
  directus_uploads:
  node_modules:
  pg_database: